### PR TITLE
Update __main__.py

### PR DESCRIPTION
**Pull request by tnwaps**
Test

### CODE REVIEW

**Comment by prono69** [comment]
U nub

**Comment by prono69** [comment]
Haha yes

**Comment by prono69** [comment]
But I don't wanna kill you 😭

**Comment by Phyco-Ninja** [comment]
Le AttributeError: Am i a joke to you?

**Comment by Harsh-br0** [comment]
Shit , party over 🤥

**Comment by Mohithash** [comment]
Happy birthday to yoy

**Pull request closed without merging**
